# Site settings
name: Volmerius
title: 'Volmer Campos Soares'
description: "Volmer's website. Passionate developer, music lover. Here you can find out how to find me around."
baseurl: ''
url: 'https://volmerius.com'

# Build settings
markdown: kramdown
permalinks: pretty
plugins:
  - jekyll-sitemap
